name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 21.0.6 da Oracle
        uses: actions/setup-java@v4
        with:
          java-version: '21.0.6'
          distribution: 'oracle'

      - name: Compilar código
        run: mvn clean package

      - name: Executar testes
        run: mvn test
